#连接数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/emm
    username: root
    password: admin
  #设置上传文件的最大大小
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  #配置jpa
  jpa:
    #显示SQL语句
    show-sql: false
    #自动更新数据库表
    hibernate:
      ddl-auto: update

#修改端口号
#server:
#  port: 9090
